### ISSUE TITLE
Content suggestion: Add Italian translation

### ISSUE THREAD

**Issue by mak-1** [mdn/translated-content#10253]
## What is the new suggestion?
I would like to contribute  the Italian language translation to the list of the available languages in the mozilla developer docs.

## Why is it important or useful?
The proposal is needed because MDN is one of the main web development resources and Italian is one of the main languages.

How many pages are likely to be needed?
One for each one that is present on the English tab, but as many as I can translate.

How much time do you think this work should take? A few hours? A week? A month?
It should take about one hour per page.

Will the work enable learners or professionals to achieve their goals better?
Yes. This enables Italian native language speakers more accessibility to the large MDN resource library.

Does it address critical needs in the web industry?
No.

Is the work an operational necessity, i.e. is not having it a security risk?
No.

Does the content help make the web more ethical?
 Yes.

**Comment by cw118** [comment]
Hi @mak-1, thank you for the request/suggestion. Unfortunately, as stated in [this MDN article on localization](https://hacks.mozilla.org/2021/03/mdn-localization-in-march-tier-1-locales-unfrozen-and-future-plans/), retired locales such as Italian will not be unfrozen (and thus will never be "unretired"):

> After this point, we won’t revive anything — the journey to retirement is one way. This may sound harsh, but we are taking determined steps to clean up MDN and get rid of out-of-date and out-of-remit content that has been around for years in some cases.

Grosso modo, the [Italian locale is "retired"](https://github.com/mdn/retired-content/tree/main/files/it), meaning it will no longer be displayed on MDN Web Docs, because it wasn't active enough and didn't have enough translations to be considered "tier 1".

I hope this explains everything, do not hesitate if you have questions :)

**Comment by mak-1** [comment]
Ok I understand, sadly.
