### ISSUE TITLE
Images doesn't display in Django/Home_page [es]

### ISSUE THREAD

**Issue by Graywolf9** [mdn/translated-content#10324]
Images doesn't display: https://developer.mozilla.org/es/docs/Learn/Server-side/Django/Home_page

**Comment by caugner** [comment]
I think once https://github.com/mdn/yari/pull/6644 has landed, the image url could be changed to `basic-django.png` like in the English version. 🤔

**Comment by cw118** [comment]
> I think once [mdn/yari#6644](https://github.com/mdn/yari/pull/6644) has landed, the image url could be changed to `basic-django.png` like in the English version. 🤔

If I may, only images in `{{EmbedLiveSample}}`s currently do not work unless the files are in `translated-content`, but images in other parts of a localized page (like the one that is not displayed on this page due to incorrect image url) can simply use the files from the `content` repo. Though sometimes we translate the diagrams, which requires the translated version of the image to be added to the corresponding folder in `translated-content`.

(All this to say that in cases like this one, the image will work once its url is corrected to `basic-django.png` like in en-US 😃)

**Comment by caugner** [comment]
Part of https://github.com/mdn/translated-content/issues/10400.

**Comment by Graywolf9** [comment]
Thank you so much @caugner and @cw118 

Fixed in #10474
