### ISSUE TITLE
About the Chinese translation of the Intersection Observer page in the document

### ISSUE THREAD

**Issue by eBaby-C** [mdn/translated-content#10951]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/IntersectionObserver

### What specific section or headline is this issue about?

Intersection Observer

### What information was incorrect, unhelpful, or incomplete?

![image](https://user-images.githubusercontent.com/78027982/210906894-96f95610-9b5f-4253-8a05-66ec83ef4e14.png)

Please check the translation of "root" in this page
There are two extra * in the Chinese page
May I ask if this ** is used as Markdown syntax to express emphasis?

### What did you expect to see?

either just a normal root or delete **

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/intersectionobserver`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/IntersectionObserver
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/intersectionobserver/index.md
* Last commit: https://github.com/mdn/translated-content/commit/c16d394a008b6896c078cb1b098df67166db0747
* Document last modified: 2022-10-02T22:33:30.000Z

</details>

**Comment by yin1999** [comment]
> May I ask if this ** is used as Markdown syntax to express emphasis?

Yes, this is as markdown syntax for bold or italics.

Because we haven't style it as bold or italics in [en-US document](https://github.com/mdn/content/blob/ffb20c5e9a940d083c97758cf73217e638feee1e/files/en-us/web/api/intersectionobserver/index.md?plain=1#L17). We can just remove this [here](https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/intersectionobserver/index.md?plain=1#L8).
