### ISSUE TITLE
Is it possible to add the word Perl to Selenium content?

### ISSUE THREAD

**Issue by yuki-kimoto** [mdn/translated-content#137]
I'm Perl programmer and use Selenium with Perl.

Is it possible to add the word Perl to Selenium content?

WebDriverとその言語、例えばJava、C＃、Ruby、Python、JavaScript（Node）などを使用してWebDriverと通信するのに必要なバインディングをインストール

https://developer.mozilla.org/ja/docs/Learn/Tools_and_testing/Cross_browser_testing/Your_own_automation_environment

**Comment by mfuji09** [comment]
@yuki-kimoto さん
この記事は英語版記事の日本語訳であり、現時点で英語版記事には Perl が含まれていないので、日本語訳にだけ追加することは適切ではないと思います。
もし Perl を追加することを提案されるのであれば、下記の英語版記事の修正として提案されてみてはいかがでしょうか。

This article is a Japanese translation of the English article, and since the English version does not include Perl at this time, I don't think it is appropriate to add it only to the Japanese translation.
If you would like to suggest adding Perl, you can suggest it as a correction to the English article below.

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Your_own_automation_environment

**Comment by yuki-kimoto** [comment]
ありがとうございます。

英語版のWebサイトのリポジトリを教えていただくことは可能でしょうか?

**Comment by mfuji09** [comment]
@yuki-kimoto さん
英語版のウェブサイトのリポジトリは、 mdn/content です。
このIssueは、もともとそちらのリポジトリに投稿されたものだと思いますが、ご指摘の部分のURLと引用内容が日本語版のものだったので、翻訳の問題と誤解されてこちら（mdn/translated-content）に転送されてしまったようです。
お手数ですが、こちらをクローズし、英語版の修正の提案として mdn/content でもう一度提案していただいた方が良いと思います。

**Comment by yuki-kimoto** [comment]
了解です。
