### ISSUE TITLE
[zh-cn]: fix the `{{glossary}}`s' link to zh version

### ISSUE THREAD

**Issue by tianyeeT** [mdn/translated-content#20820]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/Performance

### What specific section or headline is this issue about?

macro

### What information was incorrect, unhelpful, or incomplete?

Take the `客户端提示（英文）` for example, despite the fact that the corresponding Chinese version already exists, it just cannot redirect to Chinese.

- [ ] [客户端提示](https://developer.mozilla.org/en-US/docs/Web/HTTP/Client_hints)

Similar to this, there are also the following:

- [ ] [Beacon API](https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API)

### What did you expect to see?

The automagical redirect to Chinese version is expected.

**Comment by yin1999** [comment]
Hey @tianyeeT. This is because the redirection is not existed in [`files/zh-cn/_redirects.txt`](https://github.com/mdn/translated-content/blob/main/files/zh-cn/_redirects.txt). So it will be fall back to use the redirection defined in en-US. Which means, this page will be redirected to `en-US`.

/cc @mdn/core-dev. The current architecture of yari does not seem to allow the http server to determine whether a localized page exists. I'm not sure whether it is possible that we can create default localized redirects for localized content when building the redirect rules for serving. So that we can provide better localized redirect support without modifying the server architecture.
