### ISSUE TITLE
Separate zh-cn content team

### ISSUE THREAD

**Issue by kecrily** [mdn/translated-content#2193]
We discussed at https://github.com/mdn/yari/issues/4530 the model of mixing zh-hans and zh-hant and then providing conversion tools for distribution.

This was opposed by many users in Taiwan and elsewhere. I'm not sure if they are contributors or not, so I'll use user for now to refer to them.

I've seen a lot of people think that traditional users have difficulty reading simplified Chinese, and vice versa. And @irvin, who is a member of the @yari-content-zh team, thinks the review cumbersome or difficult.

I am quoting his original words here.

> I need to work on switching phrases, adjust the grammar of paragraphs, and in most cases, I will need to double-check the English version to ensure I (and Simplified translator) is misunderstanding anything, and actually, I'm still not satisfied with the published article.

Since many people think that zh-hans and zh-hant are more different than en-GB and en-US. Then it is clearly inappropriate for an outsider to guide an insider, as we have a significant difference in idiomatic usage.

It was clearly necessary to separate the zh-hans team, to relieve the pressure on a team that is now called zh but is in fact entirely focused on zh-hant users. And to improve the quality of the zh-hans documentation.

**Comment by pocketdr** [comment]
问一下，你有加tg上的讨论组吗？我理解你想改善中文翻译，但是和其他参与翻译的交流过吗

**Comment by komali2** [comment]
> This was opposed by many users in Taiwan and elsewhere. I'm not sure if they are contributors or not, so I'll use user for now to refer to them.

Many of us are. I've seen projects at g0v hackathons that are simply "translate MDN articles" or "translate wikipedia articles" or "translate mozilla release notes." 

> Since many people think that zh-hans and zh-hant are more different than en-GB and en-US.

This is a fact. Aren't you a native speaker of mandarin? I'm surprised you are acting like the two are comparable. Academic / documentary en-GB and en-US differ only in some spellings, such as color vs colour. We don't have totally incompatible differences like `麵` and `面`. Did I just say face or noodle? You tell me, based on what dialect you read it in lol. 

I agree that any translation efforts should be separate. Your quote of @irvin confirms this, look how much effort they have to put into changing between zh-cn and zh-tw: clearly automating this process will be ineffective.

**Comment by irvin** [comment]
I'm not sure what you would like to imply by quoting manual efforts on improving the machine conversion result of zh-cn Firefox for Developers documents into zh-tw. 

I don't agree with your opinion that the current zh team had "entirely focused on zh-hant users." In fact, it's totally the opposite. Since the yari migration, the current yari-content-zh team had reviewed and merged 316 commits on /zh-cn docs and 140 on /zh-tw docs. For the latest 25 PR, we merged 19 PR on /zh-cn docs and only 6 PR on /zh-tw locale.

**Comment by kecrily** [comment]
You have indicated that you have difficulty in reviewing the content of zh-hans, and I think this is one of the many ways in which our language.

> Since many people think that zh-hans and zh-hant are more different than en-GB and en-US. Then it is clearly inappropriate for an outsider to guide an insider, as we have a significant difference in idiomatic usage.

It made sense to split up the zh team in order to better give zh-hans users an authentic, high-quality translation. Because you are not very familiar with the grammatical forms and wording of zh-hans, you will have to consult the sources, but you may not be satisfied with the final result.

---

Yes, the current zh team may be dealing more with zh-hans content, but due to your unfamiliarity with zh-hans syntax and wording, this may result in an end result that leaves you, and zh-hans, unsatisfied.

**Comment by irvin** [comment]
The reviewer is and should not be the translator themself, the reviewer helps the translator. I'm not satisfied with my edit of the machine converted “Firefox for Developers” document is totally un-relative to my ability to review the PR on MDN, and the quality of the PRs from our beloved Chinese MDN contributors - non of them had submitted the machine conversion doc to MDN at all so far, which is some mechanism [you proposed](https://github.com/mdn/yari/issues/4530).

**Comment by kecrily** [comment]
So do you understand the vocabulary and grammar used in zh-hans?

**Comment by kpkonghk01** [comment]
A lot zh-hant users have difficulty in reading zh-hans doesn't disapprove the ability of any mdn zh-hans reviewers/contributors. 

And "a lot" in number doesn't imply they're majority. Localization is something about providing better reading experience to those minorities or people have reading preference. If what you concern is the efficiency, then everyone should use english instead of writing the same content in many languages which you considered inefficient yesterday.

If you want to prove that @irvin or other reviewers cannot do the job right, there is a need to seperate the team, please provide evidences like they delivered wrong translations before. Otherwise, shut up.

I suggest close this topic since this post and his/her last post are full of bias(almost no one agrees, a lot of pepole can give conter examples to what he/she claimed). What he/she suggested was lack of evidence/statistics and kinda disrespectful to others.

**Comment by Rumyra** [comment]
I'm closing this issue whilst we have a chance to review it properly from the mdn side  👍

**Comment by Rumyra** [comment]
We made the decision at MDN last year, to *not* use automation for translations. For a full explanation see [https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/](https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/) in particular:

>"Many folks we talked to said that automated translations wouldn’t be acceptable in their languages. Not only would they be substandard, but a lot of MDN Web Docs communities center around translating documents. If manual translations went away, those vibrant and highly involved communities would probably go away"

We're working on other improvements for all contributors and localizers, such as Markdown support. A feature for only a specific locale will not be a priority, so we'll be closing this issue permanently.
