### ISSUE TITLE
Add `Hacktoberfest` topic to the translated-content repository

### ISSUE THREAD

**Issue by audrasjb** [mdn/translated-content#2692]
I think it could be a way to get more contribution this month, then hopefully to onboard more people to the project.
We just need to add the `Hacktoberfest` topic to the repository.
More info: https://hacktoberfest.digitalocean.com/resources/maintainers

### Discussed in https://github.com/mdn/translated-content/discussions/2582

<div type='discussions-op-text'>

<sup>Originally posted by **Saionaro** September 26, 2021</sup>
Hi everyone!
What do you think to enable [hacktoberfest](https://hacktoberfest.digitalocean.com/resources/maintainers)-friendly in **translated-content**?

cc @mdn/core </div>

**Comment by ddbeck** [comment]
I apologize for not coming back to this sooner. For various reasons, we were unprepared for the prospect of including Hacktoberfest this year (particularly because of some bad experiences with previous years). For next year, I'd be happy to see this happen, provided the call for the label and a plan for reviewers is opened a couple of weeks before the start of the event. Thank you!
