### ISSUE TITLE
Issue with "Руководство часть 6: Отображение списков и детальн…": (short summary here please)

### ISSUE THREAD

**Issue by IvanyukStas** [mdn/translated-content#3698]
MDN URL: https://developer.mozilla.org/ru/docs/Learn/Server-side/Django/Generic_views

#### What information was incorrect, unhelpful, or incomplete?

Преобразования URL-адресов

```
from django.urls import path
from . import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^books/$', views.BookListView.as_view(), name='books'),
]
```
#### What did you expect to see?
```
urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^books/$', views.BookListView.as_view(), name='books'),
```
or original text from english version

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/learn/server-side/django/generic_views`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/Server-side/Django/Generic_views
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/server-side/django/generic_views/index.html
* Last commit: https://github.com/mdn/translated-content/commit/78fadee3cb122d5843eff5e2d466473688cb9c77
* Document last modified: 2022-01-14T21:49:57.000Z

</details>

**Comment by myshov** [comment]
@IvanyukStas приветствую!
Посмотрел оригинальную статью там пути задаются без регулярок:
```
urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
]
```

Я не спец по Django, но кажется, что между предложенным вариантом и вариантом в английской версии нет принципиальных отличий?

**Comment by me12345ghru** [comment]
Thanks

**Comment by IvanyukStas** [comment]
как я понимаю тутор должен быть актуальным в использовании, функции url() в последней джанге нет, его заменили на re_path(), разница для новичков думаю значительная, когда пишут про реджекс и используют устаревшую функцию

**Comment by IvanyukStas** [comment]
> @IvanyukStas в новой версии Django есть функция `path` как в прцитированном мною коде?

да, есть

**Comment by myshov** [comment]
@IvanyukStas то есть этот код можно использовать вместо старого кода с `url`? Дело в том, что если мы хотим заменить на пример с `re_path`, то это будет немного сложнее, так как надо будет обновить ещё английскую версию статьи.

**Comment by sashasushko** [comment]
Я добавил ярлык "отличная задача для начала". Буду рад, если кто-то возьмётся за неё.

Что нужно сделать:
- взять из [англоязычной статьи](https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/generic_views/index.md) раздел _URL mapping_
- перенести его в русскоязычную статью вместо блока _Преобразования URL-адресов_
- перевести на русский

---

I've added the label "good first issue". I would be glad if someone would take it on.

What needs to be done:
- take from the [English article](https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/django/generic_views/index.md) block _URL mapping_
- transfer it to ru-locale instead of _Преобразования URL-адресов_ block
- translate into russian

---

Может быть вы сами, @IvanyukStas, готовы?
