### ISSUE TITLE
Issue with "500 Internal Server Error": (short summary here please)

### ISSUE THREAD

**Issue by lailaebr** [mdn/translated-content#3785]
MDN URL: https://developer.mozilla.org/fr/docs/Web/HTTP/Status/500

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/http/status/500`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/HTTP/Status/500
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/http/status/500/index.md
* Last commit: https://github.com/mdn/translated-content/commit/d3dbfce79ad140b58898518250a5a75195692550
* Document last modified: 2022-01-20T18:15:19.000Z

</details>

**Comment by cw118** [comment]
@lailaebr @myshov hope you don't mind me pinging — I've looked over the page and based on what I saw, the pull request I created with various fixes for French HTTP files should resolve all issues with the `500 Internal Server Error` page. Since no template information was provided here, I'll be linking that PR.
