### ISSUE TITLE
FR - String.prototype.split()

### ISSUE THREAD

**Issue by ElMaxonDSCRD** [mdn/translated-content#387]
There is an issue on the french `split` page, 69th line: https://github.com/mdn/translated-content/blob/8ce2f87d3fcc5c07610f135e4f759088d84c4d4f/files/fr/web/javascript/reference/global_objects/string/split/index.html#L69

There is a `print` function, where there should be a `console.log()` or simply `join()`.

The US version of the page is fine:
`console.log('The array has ', arrayOfStrings.length, ' elements: ', arrayOfStrings.join(' / '))`
instead of 
```console.log("Le tableau comporte " + arrayOfStrings.length + " elements : ");

  for (var i=0; i < arrayOfStrings.length; i++)
    print(arrayOfStrings[i] + " / ");```

Thank you, Maxon

**Comment by tristantheb** [comment]
Hi @ElMaxonDSCRD,

Thanks for your report! 🙂
If you wish, you can contribute to the updating of this page by following the exmplications available at the following link: https://tech.mozfr.org/post/2021/03/16/MDN-sur-GitHub-comment-contribuer

Otherwise, a FR contributor will take care of this page in order to realign it with the en-US version 😉

**Comment by ElMaxonDSCRD** [comment]
Thank you for your answer! I'll contribute asap 👍
