### ISSUE TITLE
Issue with "Notre premier code JavaScript"

### ISSUE THREAD

**Issue by Cowkill** [mdn/translated-content#388]
MDN URL: https://developer.mozilla.org/fr/docs/Learn/JavaScript/First_steps/A_first_splash

#### What information was incorrect, unhelpful, or incomplete?
Hi people ! Just to report an tiny little error on this section, in french language.

#### Specific section or headline?
https://developer.mozilla.org/fr/docs/Learn/JavaScript/First_steps/A_first_splash#jouer_avec_les_objets_du_navigateur

Last example (number 8), the text justification is out of place (on the right) so the lines are not correct in appearance.
For instance : 

> guesses.style.backgroundColor = 'yellow';

  appears as :

> ;'guesses.style.backgroundColor = 'yellow

Not a real issue since copy/past works fine.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/learn/javascript/first_steps/a_first_splash`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/JavaScript/First_steps/A_first_splash
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/javascript/first_steps/a_first_splash/index.html
* Last commit: https://github.com/mdn/translated-content/commit/f3af7db28fef073578fe2d432ac976ed993faa5f
* Document last modified: 2021-03-28T17:28:29.000Z

</details>

**Comment by SphinxKnight** [comment]
This is due to this line wrongly using the `dir` attribute https://github.com/mdn/translated-content/blob/1c31837f5147fb64bf4c43566b9430203372fed2/files/fr/learn/javascript/first_steps/a_first_splash/index.html#L697

@Cowkill, would you be interested in fixing this? :) (https://tech.mozfr.org/post/2021/03/16/MDN-sur-GitHub-comment-contribuer might be a good introduction if help is needed)

**Comment by Cowkill** [comment]
Thanks a lot ! I'd gladly help when needed.
