### ISSUE TITLE
Issue with "Array.prototype.copyWithin()": (short summary here please)

### ISSUE THREAD

**Issue by zbdx-xin** [mdn/translated-content#5993]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/copyWithin

#### What information was incorrect, unhelpful, or incomplete?
the problem is 
![1](https://user-images.githubusercontent.com/59362944/170876177-a3d5828d-2497-4464-b6a0-7dd3c24be966.jpeg)

#### Specific section or headline?
  this result should be [a,...], not is [d,...].

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/array/copywithin`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/copyWithin
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/array/copywithin/index.html
* Last commit: https://github.com/mdn/translated-content/commit/0e2f75894a3c72fb155cd78b5dd535d2c1932d7f
* Document last modified: 2022-04-08T14:17:48.000Z

</details>

**Comment by cw118** [comment]
Hi @zbdx-xin, the interactive example/comment is correct. 

The `copyWithin()` method *overwrites* existing values, meaning after the line `console.log(array1.copyWithin(0, 3, 4));`, the value of `array1` *becomes* `["d", "b", "c", "d", "e"]`. 

So, the second `copyWithin()` is taking `["d", "b", "c", "d", "e"]` as the value of `array1` and *not* the original array of `['a', 'b', 'c', 'd', 'e']`.

<details>
<summary>You can also test and see this in the console:</summary>

![image](https://user-images.githubusercontent.com/87150472/170877304-66774702-7ca5-40cb-8c39-835905201331.png)

</details>

I'll close this because there is not a mistake, but don't hesitate to discuss/ask questions :)

**Comment by zbdx-xin** [comment]
Thank you for your reply. I have realized my mistake. I sincerely apologize to you





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mdn/translated-content"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月29日(星期天) 晚上11:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mdn/translated-content] Issue with "Array.prototype.copyWithin()": (short summary here please) (Issue #5993)





 
Hi @zbdx-xin, the interactive example/comment is correct.
 
The copyWithin() method overwrites existing values, meaning after the line console.log(array1.copyWithin(0, 3, 4));, the value of array1 becomes ["d", "b", "c", "d", "e"].
 
So, the second copyWithin() is taking ["d", "b", "c", "d", "e"] as the value of array1 and not the original array of ['a', 'b', 'c', 'd', 'e'].
  You can also test and see this in the console: 

  
I'll close this because there is not a mistake, but don't hesitate to discuss/ask questions :)

**Comment by cw118** [comment]
No need to apologize! Best wishes :)
