### ISSUE TITLE
Issue with "File.name": Should be stated that JSON.stringify() will ignore this property

### ISSUE THREAD

**Issue by albertnev** [mdn/translated-content#6673]
MDN URL: https://developer.mozilla.org/es/docs/Web/API/File/name

#### What information was incorrect, unhelpful, or incomplete?
If we try to send a file in a fetch request that uses JSON, or we just try to `JSON.stringify()` a File object, the `name` property will be ignored. The `path` property is kept in the JSON information - and as far as I can tell, they have the same content -, but the `name` will be skipped. However, the `path` property is nowhere described in the documentation, while the `name` prop is.

#### Specific section or headline?
File.name

#### What did you expect to see?
Information about its compatibility with `JSON.stringify()`, since this can lead to errors in communication with APIs and requests, as well as in third-party libraries (such as Typescript, which does not include the `path` prop in its `File` definition).

#### Did you test this? If so, how?
Created a form with a file input and an `onChange` handler like this: 
`console.log("Original object: ", file); console.log("Serialized object: ", JSON.stringify(file));`

<details>
<summary>Page report details</summary>

* Folder: `es/web/api/file/name`
* MDN URL: https://developer.mozilla.org/es/docs/Web/API/File/name
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/api/file/name/index.html
* Last commit: https://github.com/mdn/translated-content/commit/1109132f09d75da9a28b649c7677bb6ce07c40c0
* Document last modified: 2020-12-08T19:41:45.000Z

</details>

**Comment by marcelozarate** [comment]
@albertnev thanks for reporting! Even though your report metions the MDN URL: https://developer.mozilla.org/es/docs/Web/API/File/name (related to the spanish translation of mdn content) it seems that the issue you are raising is far more related to the content itself, rather than the translation. You can copy and report again your issue here: https://github.com/mdn/content/issues/new/choose

Let us know! If time passes and you do not take action, this issue will be closed.
