### ISSUE TITLE
Issue with "element": (short summary here please)

### ISSUE THREAD

**Issue by v1nce** [mdn/translated-content#8087]
MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/element

I'd like this url to provide a sample of reflection box (https://developer.mozilla.org/fr/docs/Web/CSS/-webkit-box-reflect) which "is missing" in firefox

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/element`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/element
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/element/index.md
* Last commit: https://github.com/mdn/translated-content/commit/39bc2807bc2ec8bdb4db1066a302a14ce50d7acf
* Document last modified: 2022-06-17T05:30:41.000Z

</details>

**Comment by cw118** [comment]
Hi @v1nce, could you please provide more details on the issue(s) you were facing?

**Comment by v1nce** [comment]
This is NOT a FR issue. I forgot to remove the FR in the url but problem is the same with english site.

What can I add more ? 
FF lacks cool features of other browsers, like the reflection effect (for the instance).
So rather than a so-so sample for "element" I'd like to see a firefox polyfill for the -webkit-box-reflect.

**Comment by cw118** [comment]
Thank you for the explanation. Since English content is the reference for French pages, I think it would be best to create an issue on [`mdn/content`](https://github.com/mdn/content) *(the `translated-content` repository is only for translations, not for English pages)* or a [discussion on `mdn/mdn-community`](https://github.com/mdn/mdn-community/discussions) to see what can be done or added.

I will close this (at least for now), don't hesitate if help is needed :)
