### ISSUE TITLE
typos in french version

### ISSUE THREAD

**Issue by voronamanga** [mdn/translated-content#97]
https://developer.mozilla.org/fr/docs/Web/API/Element/getBoundingClientRect :
Title "Syntaxe", subtitle "Valeur de retour", § mdn/content#2: "est définit" -> "est défini" (grammar);
Title "Spécifications", subtitle "Notes", § mdn/content#2: "problèmes de comptabilité" -> "problèmes de compatibilité" (typo).

**Comment by chrisdavidmills** [comment]
@SphinxKnight moved! I also had a look, and it turns out that to transfer issues you need write permissions on both the "from" and "to" repositories. So I've just given you write permissions on this one as well.

You should start to see a "Transfer issue" link in the right-hand column of issues, near the bottom.
