### ISSUE TITLE
MDN Web Docs (white-space) doesnt have the first live sample

### ISSUE THREAD

**Issue by Gianluca-w** [mdn/translated-content#9979]
### MDN URL

https://developer.mozilla.org/es/docs/Web/CSS/white-space

### What specific section or headline is this issue about?

First Live sample is missing

### What information was incorrect, unhelpful, or incomplete?

Live sample was not alive when i tried to search for it

### What did you expect to see?

I expected to see the live example

### Do you have any supporting links, references, or citations?

Live sample failed!

An error occurred trying to render this live sample.
Consider filing an issue or trying your hands at a fix of your own.

Error details:

KumascriptError: unable to find any live code samples for "white-space" within /es/docs/Web/CSS/white-space 

### Do you have anything more you want to share?

Good luck.
I currently use Ubuntu 20 + Latest Firefox (untill 18/November/2022)

**Comment by cw118** [comment]
The `{{EmbedLiveSample}}` macro sometimes has strange/unexpected behavior on translated-content (I think the [title argument](https://github.com/mdn/translated-content/blob/main/files/es/web/css/white-space/index.md?plain=1#L154) is incorrect, it should be "Ejemplo" or an empty string "" instead of "white-space"), but fortunately it seems that updating the page will remove this error :)

**Comment by Graywolf9** [comment]
Thank you so much for submitting the issue @Gianluca-w !

And thank you for your attentions @bsmth and @cw118
